### ISSUE TITLE
Masternode reward calculated the wrong way

### ISSUE THREAD

**Issue by OwenRay** [zocteam/zeroonediscordbot#4]
https://github.com/zocteam/zeroonediscordbot/blob/3ecd9cfd8b61722f5d094063b2aa3a86d7ef6fd3/comands.js#L89  

`(60/2.5*24)/result`  

60/2.5*24 is the number of blocks mined per day. if you divide that by the number of masternodes then you have the average reward per masternode per day

**Comment by Evydder** [comment]
Issue is fixed in commit 33e6bce73d0d9de8cb8d3eb78627f405afa93105
